### ISSUE TITLE
Error running aviglitch

### ISSUE THREAD

**Issue by tmargolis** [fand/node-aviglitch#1]
I've tried running both the datamosh script as well as a node JS file and am getting the same error with both:

```
$ datamosh -f Separated\ LR\ eyes/086L.avi -o ./Deiframed/086L.avi
/usr/local/lib/node_modules/aviglitch/lib/aviglitch/frames.js:446
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                                ^

TypeError: Cannot read property 'length' of undefined
    at Frames.fix_offsets_if_needed (/usr/local/lib/node_modules/aviglitch/lib/aviglitch/frames.js:446:33)
    at new Frames (/usr/local/lib/node_modules/aviglitch/lib/aviglitch/frames.js:53:12)
    at new Base (/usr/local/lib/node_modules/aviglitch/lib/aviglitch/base.js:29:21)
    at Function.AviGlitch.open (/usr/local/lib/node_modules/aviglitch/lib/aviglitch.js:27:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/aviglitch/bin/datamosh.js:57:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I've tried with several AVI files. I'm using nodejs v4.4.3
Any help would be greatly appreciated! I've got over 100 files to mosh :)

**Comment by fand** [comment]
it seems to be a simple bug, but I can't reprduce it...
Could you give me some of the files? It would help me to fix it 😺

**Comment by fand** [comment]
I published v0.2.0 today.
Do the errors still happen?
