### ISSUE TITLE
datamosh does not create a tmp folder auto

### ISSUE THREAD

**Issue by coral** [fand/node-aviglitch#3]
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Volumes/Disk/test/glitch/tmp/0'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at new IO (/usr/local/lib/node_modules/aviglitch/lib/io.js:51:28)
    at Function.IO.temp (/usr/local/lib/node_modules/aviglitch/lib/io.js:182:10)
    at new Base (/usr/local/lib/node_modules/aviglitch/lib/base.js:50:30)
    at Function.open (/usr/local/lib/node_modules/aviglitch/lib/aviglitch.js:60:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/aviglitch/bin/datamosh.js:52:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Creating the folder manually work.

I recommend using https://github.com/substack/node-mkdirp here

**Comment by fand** [comment]
Thanks for report! 😸 
fixed in https://github.com/fand/node-aviglitch/commit/12a97e410c5d791eab858855a0527e45b81d8127
